# Produção
spring.application.name=auth-server

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}

api.security.token.secret=${JWT_SECRET}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER}

# spring.h2.console.enabled=true
# spring.h2.console.settings.web-allow-others=true