spring.application.name=auth-server
server.port=8081

spring.config.import=optional:file:.env[.properties]

# Banco de Dados Local (Padrão)
# Se as variáveis de ambiente não estiverem definidas, usa os valores padrão do localhost
spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USERNAME}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Segurança
api.security.token.secret=${JWT_SECRET}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER}

# JPA/Hibernate
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origin=${VITE_URL}
