# Configuração para Azure
# Este perfil será ativado com -Dspring.profiles.active=azure ou SPRING_PROFILES_ACTIVE=azure

# No Azure, as variáveis de ambiente DEVEM ser configuradas no portal
spring.datasource.url=${DB_URL_AZURE}
spring.datasource.username=${DB_USERNAME_AZURE}
spring.datasource.password=${DB_PASSWORD_AZURE}

api.security.token.secret=${JWT_SECRET}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER}

# Em produção, geralmente desativamos logs de SQL excessivos
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
