spring.application.name=auth-server
server.port=8081

spring.config.import=optional:file:.env[.properties]

# Banco de Dados Local (Padrão)
# Se as variáveis de ambiente não estiverem definidas, usa os valores padrão do localhost
spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USERNAME}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Segurança
api.security.token.secret=${JWT_SECRET}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER}

# JPA/Hibernate
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origin=${VITE_URL}

app.upload.dir=${UPLOAD_DIR}

# # ============================================
# # CONFIGURAÇÕES DO APACHE KAFKA (PRODUCER)
# # ============================================

# Habilita o Kafka por padrão ou permite desativar localmente
app.kafka.enabled=false

# Endereço dos brokers do Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Serializadores de chave e valor
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Mapeamento do tipo de evento JSON
spring.kafka.producer.properties.spring.json.type.mapping=userCreatedEvent:com.api.authserver.domain.dtos.user.events.UserCreatedEventDTO
# Garantia de entrega (acks=all garante confirmação de todas as réplicas)
# Eclusivo de quem produz
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Nome do Tópico customizado
app.kafka.topics.user-created=user-created-topic