# Configurações para desenvolvimento local (Docker ou Nativo)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_server_db
spring.datasource.username=montoril
spring.datasource.password=Raquel1407@

api.security.token.secret=minha_chave_bem_secreta
api.security.token.issuer=auth-server-api

# Exibir SQL no console para facilitar o debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
