# Configurações para desenvolvimento local (Docker ou Nativo)
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_server_db
spring.datasource.username=montoril
spring.datasource.password=Raquel1407@

# Exibir SQL no console para facilitar o debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
