CREATE TABLE IF NOT EXISTS users(
    id CHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password CHAR(8) NOT NULL,
    created_at TIMESTAMP NOT NULL
)